### ISSUE TITLE
Add header and footer to #drilldowninfo

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticDrilldown#40]
https://phabricator.wikimedia.org/T135626

**Comment by kghbln** [comment]
Refs https://github.com/SemanticMediaWiki/SemanticDrilldown/issues/21?

**Comment by gesinn-it-gea** [comment]
This is covered by tests: https://github.com/SemanticMediaWiki/SemanticDrilldown/blob/master/tests/phpunit/Integration/JSONScript/TestCases/header-footer.json as well as documented https://www.mediawiki.org/w/index.php?title=Extension%3ASemantic_Drilldown&diff=6863505&oldid=6863498
