### ISSUE TITLE
Semantic Drilldown Browse Data does not return output 

### ISSUE THREAD

**Issue by Kolophonium0** [SemanticMediaWiki/SemanticDrilldown#41]
started from old repo.

**Comment by Kolophonium0** [comment]
All pages with property 'Beruf' are in the category person (with a set template and form). The above #drilldowninfo is currently on this category page. The property 'Beruf' is a property of the datatype page.

**Comment by Kolophonium0** [comment]
This should get me 1 result.
![image](https://user-images.githubusercontent.com/24278823/216027016-c82d18b7-3527-4904-9014-af085f9386bb.png)

**Comment by gesinn-it-gea** [comment]
Maybe you are missing the `display parameters` in `#drilldowninfo`

**Comment by Kolophonium0** [comment]
I fixed it by adding as you suggested: display parameters. Without it it wont show any results. Is this normally a needed parameter? Because the manual announces that this is optional. Furthermore i changed to hidecategoriesbydefault and used the opt-in solution, because otherwise it just showed 1 random category without a #drilldowninfo.

**Comment by Kolophonium0** [comment]
Thanks a lot btw!

**Comment by gesinn-it-gea** [comment]
We are about to improve the originial manual. Thanks for your feedback and patience. Good to hear, it's working now.

**Comment by Kolophonium0** [comment]
Update: If i just put something thats not existing in the display parameters, it works like described without the display parameters.
