### ISSUE TITLE
Overwriting of getSQL() is deprecated

### ISSUE THREAD

**Issue by YvarRavy** [SemanticMediaWiki/SemanticDrilldown#73]
`Deprecated: SD\Specials\BrowseData\QueryPage overrides getSQL which was deprecated in MediaWiki 1.39. [Called from QueryPage::execute in /var/platform/cores/1.39/20231206-0951/includes/specialpage/QueryPage.php at line 727] in /var/platform/cores/1.39/20231206-0951/includes/debug/MWDebug.php on line 381`
when on "Special:BrowseData"

**Comment by gesinn-it-gea** [comment]
this is also reported by CI: https://github.com/SemanticMediaWiki/SemanticDrilldown/actions/runs/7141658667/job/19449339877#step:4:1347 (with some other deprecation warnings)

**Comment by gesinn-it-gea** [comment]
https://phabricator.wikimedia.org/T244138

**Comment by YOUR1** [comment]
Weird that this is labeled enhancement, seems more like a bug to me.

**Comment by gesinn-it-gea** [comment]
Fixing deprecations can be categorized as both a bug fix and an enhancement, depending on the context and the nature of the changes.

## Bug Fix:
If the deprecation is causing the software to behave incorrectly or causing errors, addressing it would be considered a bug fix. Deprecations often indicate that certain features or practices are no longer recommended and may be removed in future versions. Ignoring these deprecations can lead to issues, so fixing them can be seen as resolving existing problems in the code.

## Enhancement:
On the other hand, addressing deprecations can also be viewed as an enhancement. By updating the code to use newer, recommended practices, you are improving the codebase's overall quality, maintainability, and future-proofing it. This kind of change may not be fixing a specific bug, but it enhances the codebase by making it more aligned with current best practices and reducing technical debt.

:-)

**Comment by krabina** [comment]
Solved via #74
